<?php

declare(strict_types=1);

namespace Facet\Database;

use Closure;
use Facet\Config\Config;
use PDO;
use PDOException;
use PDOStatement;
use Throwable;

/**
 * The single place in Facet that talks to MariaDB.
 *
 * Everything above this class works in application terms: it passes SQL and an
 * array of parameters, and receives arrays or a row count. It never sees a
 * {@see PDO} object it has to configure correctly, never has to remember to
 * turn exceptions on, and never receives a {@see PDOException} whose message
 * names the account that failed to authenticate.
 *
 * Connection is lazy. The public site is file-backed and must keep rendering
 * with no database configured at all, so constructing this object — or wiring
 * it into a container — costs nothing until a query is actually run.
 */
final class Database
{
    private DatabaseCredentials $credentials;

    private ?PDO $pdo = null;

    public function __construct(DatabaseCredentials $credentials)
    {
        $this->credentials = $credentials;
    }

    public static function fromConfig(Config $config): self
    {
        return new self(DatabaseCredentials::fromConfig($config));
    }

    /**
     * Connection options that the rest of the codebase is entitled to assume.
     *
     * - `ERRMODE_EXCEPTION` so a failed statement can never be mistaken for an
     *   empty result set.
     * - `FETCH_ASSOC` so rows are read by column name and never by position.
     * - `EMULATE_PREPARES => false` so parameters are bound by the server
     *   rather than interpolated into SQL by the driver. This is what makes
     *   {@see select()} and friends structurally injection-proof rather than
     *   merely well-escaped.
     * - `STRINGIFY_FETCHES => false` so an `INT` column arrives as an int.
     *
     * @return array<int, mixed>
     */
    public static function options(): array
    {
        return [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
            PDO::ATTR_STRINGIFY_FETCHES => false,
        ];
    }

    /**
     * @throws DatabaseException when the connection cannot be established
     */
    public function pdo(): PDO
    {
        return $this->pdo ??= $this->connect();
    }

    public function isConnected(): bool
    {
        return $this->pdo !== null;
    }

    /**
     * Drop the connection. The next call re-establishes it.
     */
    public function disconnect(): void
    {
        $this->pdo = null;
    }

    /**
     * @param array<string, mixed> $parameters
     *
     * @return list<array<string, mixed>>
     *
     * @throws DatabaseException
     */
    public function select(string $sql, array $parameters = []): array
    {
        /** @var list<array<string, mixed>> $rows */
        $rows = $this->run($sql, $parameters)->fetchAll(PDO::FETCH_ASSOC);

        return $rows;
    }

    /**
     * @param array<string, mixed> $parameters
     *
     * @return array<string, mixed>|null
     *
     * @throws DatabaseException
     */
    public function selectOne(string $sql, array $parameters = []): ?array
    {
        $row = $this->run($sql, $parameters)->fetch(PDO::FETCH_ASSOC);

        /** @var array<string, mixed>|false $row */
        return $row === false ? null : $row;
    }

    /**
     * @param array<string, mixed> $parameters
     *
     * @throws DatabaseException
     */
    public function selectValue(string $sql, array $parameters = []): mixed
    {
        $value = $this->run($sql, $parameters)->fetchColumn();

        return $value === false ? null : $value;
    }

    /**
     * Run a write and report how many rows it touched.
     *
     * @param array<string, mixed> $parameters
     *
     * @throws DatabaseException
     */
    public function execute(string $sql, array $parameters = []): int
    {
        return $this->run($sql, $parameters)->rowCount();
    }

    /**
     * Run developer-authored SQL that carries no user input.
     *
     * This is the one entry point that does not prepare, because it exists for
     * schema statements: MariaDB cannot prepare much of DDL, and a migration's
     * text comes from the repository rather than from a request. Never reach
     * for it with a value that came from outside the codebase.
     *
     * @throws DatabaseException
     */
    public function executeTrusted(string $sql): void
    {
        try {
            $this->pdo()->exec($sql);
        } catch (PDOException $e) {
            throw DatabaseException::queryFailed($sql, $e, $this->credentials);
        }
    }

    /**
     * The id generated by the last INSERT on this connection.
     *
     * Null when the driver has none to report — the table has no
     * AUTO_INCREMENT column, or nothing has been inserted yet. Callers that
     * require an id must say so themselves rather than trust a sentinel.
     */
    public function lastInsertId(): ?string
    {
        $id = $this->pdo()->lastInsertId();

        return $id === false ? null : $id;
    }

    /**
     * Run a closure inside a transaction, rolling back on any throwable.
     *
     * Note that this guarantees atomicity for DML only. MariaDB commits DDL
     * implicitly, so a migration that alters schema is *not* made atomic by
     * wrapping it here.
     *
     * @template T
     *
     * @param Closure(self): T $work
     *
     * @return T
     *
     * @throws DatabaseException
     */
    public function transaction(Closure $work): mixed
    {
        $pdo = $this->pdo();

        try {
            $pdo->beginTransaction();
        } catch (PDOException $e) {
            throw DatabaseException::transactionFailed($e, $this->credentials);
        }

        try {
            $result = $work($this);
            $pdo->commit();

            return $result;
        } catch (Throwable $e) {
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }

            throw $e;
        }
    }

    /**
     * @param array<string, mixed> $parameters
     *
     * @throws DatabaseException
     */
    private function run(string $sql, array $parameters): PDOStatement
    {
        try {
            $statement = $this->pdo()->prepare($sql);
            $statement->execute($parameters === [] ? null : $parameters);

            return $statement;
        } catch (PDOException $e) {
            throw DatabaseException::queryFailed($sql, $e, $this->credentials);
        }
    }

    /**
     * @throws DatabaseException
     */
    private function connect(): PDO
    {
        try {
            return new PDO(
                $this->credentials->dsn(),
                $this->credentials->username(),
                $this->credentials->password(),
                self::options()
            );
        } catch (PDOException $e) {
            throw DatabaseException::connectionFailed($e, $this->credentials);
        }
    }

    /**
     * Keeps a stray `var_dump()` of the connection from printing credentials.
     *
     * @return array<string, mixed>
     */
    public function __debugInfo(): array
    {
        return [
            'credentials' => $this->credentials->__debugInfo(),
            'connected' => $this->isConnected(),
        ];
    }
}
